### ISSUE TITLE
Format dbs to match OpSim outputs

### ISSUE THREAD

**Issue by humnaawan** [yoachim/SLAIR_runs#1]
@yoachim is there any way the SLAIR output table and column names can be matched to those in OpSim? I am able to circumvent the column names not matching (`RA` vs. `fieldRA`, `dec` vs. `fieldDec`, `fivesigmadepth` vs. `fiveSigmaDepth`) and SLAIR outputs missing some attributes like `fetchPropInfo` and `raDecInDeg`. However, SLAIR table name is `observations` and MAF metricBundle wants `SummaryAllProps`.

If you know any way to get MAF to read in SLAIR outputs, please let me know. I've invested quite a bit of time in figuring this out already and I wanted to check in with you before attempting to write SQL queries to chance the db files.

**Comment by yoachim** [comment]
Yes, these runs use the `speedObservatory` package, and thus have a non-standard schema. Here's an example script that connects to the database and then sets the new schema for MAF batches:

https://github.com/yoachim/SLAIR_runs/blob/master/runs/run_glance.py
